packages:
  - apps/*
  - packages/*

catalog:
  '@better-auth/cli': ^1.4.17
  '@better-auth/expo': ^1.4.17
  '@kyh/eslint-config': ^1.1.13
  '@kyh/prettier-config': ^1.1.13
  '@kyh/tsconfig': ^1.1.13
  '@tailwindcss/postcss': ^4.1.18
  '@tailwindcss/vite': ^4.1.18
  '@tanstack/react-form': ^1.27.7
  '@tanstack/react-query': ^5.90.20
  '@trpc/client': ^11.8.1
  '@trpc/server': ^11.8.1
  '@trpc/tanstack-react-query': ^11.8.1
  '@types/node': ^24.10.9
  '@types/react': ^19.2.9
  '@types/react-dom': ^19.2.3
  '@vitejs/plugin-react': ^5.1.2
  better-auth: ^1.4.17
  eslint: ^9.39.2
  next: ^16.1.4
  prettier: ^3.8.1
  react: ^19.2.3
  react-dom: ^19.2.3
  superjson: ^2.2.6
  tailwindcss: ^4.1.18
  typescript: ^5.9.3
  vite: ^7.3.1
  zod: ^4.3.6

linkWorkspacePackages: true

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - better-sqlite3
  - es5-ext
  - esbuild
  - sharp

publicHoistPattern:
  - '@ianvs/prettier-plugin-sort-imports'
  - prettier-plugin-tailwindcss
