packages:
  - apps/*
  - packages/*

catalog:
  '@better-auth/cli': ^1.4.19
  '@better-auth/expo': ^1.4.19
  '@kyh/eslint-config': ^1.1.13
  '@kyh/prettier-config': ^1.1.13
  '@kyh/tsconfig': ^1.1.13
  '@tailwindcss/postcss': ^4.2.1
  '@tailwindcss/vite': ^4.2.1
  '@tanstack/react-form': ^1.28.3
  '@tanstack/react-query': ^5.90.21
  '@trpc/client': ^11.10.0
  '@trpc/server': ^11.10.0
  '@trpc/tanstack-react-query': ^11.10.0
  '@types/node': ^24.10.14
  '@types/react': ^19.2.14
  '@types/react-dom': ^19.2.3
  '@vitejs/plugin-react': ^5.1.4
  better-auth: ^1.4.19
  eslint: ^9.39.3
  next: ^16.1.6
  prettier: ^3.8.1
  react: ^19.2.4
  react-dom: ^19.2.4
  superjson: ^2.2.6
  tailwindcss: ^4.2.1
  typescript: ^5.9.3
  vite: ^7.3.1
  zod: ^4.3.6

linkWorkspacePackages: true

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - better-sqlite3
  - es5-ext
  - esbuild
  - sharp

publicHoistPattern:
  - '@ianvs/prettier-plugin-sort-imports'
  - prettier-plugin-tailwindcss
