packages:
  - apps/*
  - packages/*
  - content/*

catalog:
  "@kyh/eslint-config": ^1.1.10
  "@kyh/prettier-config": ^1.1.10
  "@kyh/tsconfig": ^1.1.10
  "@tanstack/react-query": ^5.90.5
  "@trpc/client": ^11.6.0
  "@trpc/server": ^11.6.0
  "@trpc/tanstack-react-query": ^11.6.0
  "@types/node": ^24.9.1
  "@types/react": ^19.2.2
  "@types/react-dom": ^19.2.2
  eslint: ^9.38.0
  next: ^16.0.0
  prettier: ^3.6.2
  react: ^19.2.0
  react-dom: ^19.2.0
  superjson: ^2.2.3
  typescript: ^5.9.3
  zod: ^4.1.12

linkWorkspacePackages: true

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - better-sqlite3
  - es5-ext
  - esbuild
  - sharp
