import React from "react";
import Head from "next/head";
import SiteLayout from "components/SiteLayout";
import HeroSection from "components/HeroSection";
import SectionHeader from "components/SectionHeader";
import TextHeader from "components/TextHeader";
import TextParagraph from "components/TextParagraph";
import TextList from "components/TextList";

const Content = () => (
  <>
    <TextParagraph>
      <small>Effective date: 2021-04-14</small>
    </TextParagraph>
    <TextParagraph>
      Kaiyu Hsu (“I”, “me”, “us”, “we”, or “our”) operates https://uicapsule.com
      (hereinafter referred to as “Service”).
    </TextParagraph>
    <TextParagraph>
      Our Privacy Policy governs your visit to https://uicapsule.com, and
      explains how we collect, safeguard and disclose information that results
      from your use of our Service.
    </TextParagraph>
    <TextParagraph>
      We use your data to provide and improve Service. By using Service, you
      agree to the collection and use of information in accordance with this
      policy. Unless otherwise defined in this Privacy Policy, the terms used in
      this Privacy Policy have the same meanings as in our Terms and Conditions.
    </TextParagraph>
    <TextParagraph>
      Our Terms and Conditions (“Terms”) govern all use of our Service and
      together with the Privacy Policy constitutes your agreement with us
      (“agreement”).
    </TextParagraph>
    <TextHeader>Definitions</TextHeader>
    <TextList as="ul">
      <li>
        <strong>SERVICE</strong> means the https://uicapsule.com website
        operated by UI Capsule.
      </li>
      <li>
        <strong>PERSONAL DATA</strong> means data about a living individual who
        can be identified from those data (or from those and other information
        either in our possession or likely to come into our possession).
      </li>
      <li>
        <strong>USAGE DATA</strong> is data collected automatically either
        generated by the use of Service or from Service infrastructure itself
        (for example, the duration of a page visit).
      </li>
      <li>
        <strong>COOKIES</strong> are small files stored on your device (computer
        or mobile device).
      </li>
      <li>
        <strong>DATA CONTROLLER</strong> means a natural or legal person who
        (either alone or jointly or in common with other persons) determines the
        purposes for which and the manner in which any personal data are, or are
        to be, processed. For the purpose of this Privacy Policy, we are a Data
        Controller of your data.
      </li>
      <li>
        <strong>DATA PROCESSORS (OR SERVICE PROVIDERS)</strong> means any
        natural or legal person who processes the data on behalf of the Data
        Controller. We may use the services of various Service Providers in
        order to process your data more effectively.
      </li>
      <li>
        <strong>DATA SUBJECT</strong> is any living individual who is the
        subject of Personal Data.
      </li>
      <li>
        <strong>THE USER</strong> is the individual using our Service. The User
        corresponds to the Data Subject, who is the subject of Personal Data.
      </li>
    </TextList>
    <TextHeader>Information Collection and Use</TextHeader>
    <TextParagraph>
      We collect several different types of information for various purposes to
      provide and improve our Service to you.
    </TextParagraph>
    <TextParagraph>
      <div>
        <strong>Personal Data</strong>
      </div>
      While using our Service, we may ask you to provide us with certain
      personally identifiable information that can be used to contact or
      identify you (“Personal Data”). Personally identifiable information may
      include, but is not limited to:
    </TextParagraph>
    <TextParagraph>
      <div>
        <strong>Cookies and Usage Data</strong>
      </div>
      We may use your Personal Data to contact you with newsletters, marketing
      or promotional materials and other information that may be of interest to
      you. You may opt out of receiving any, or all, of these communications
      from us by following the unsubscribe link.
    </TextParagraph>
    <TextParagraph>
      <div>
        <strong>Usage Data</strong>
      </div>
      We may also collect information that your browser sends whenever you visit
      our Service or when you access Service by or through a mobile device
      (“Usage Data”).
    </TextParagraph>
    <TextParagraph>
      This Usage Data may include information such as your computer's Internet
      Protocol address (e.g. IP address), browser type, browser version, the
      pages of our Service that you visit, the time and date of your visit, the
      time spent on those pages, unique device identifiers and other diagnostic
      data.
    </TextParagraph>
    <TextParagraph>
      When you access Service with a mobile device, this Usage Data may include
      information such as the type of mobile device you use, your mobile device
      unique ID, the IP address of your mobile device, your mobile operating
      system, the type of mobile Internet browser you use, unique device
      identifiers and other diagnostic data.
    </TextParagraph>
    <TextParagraph>
      <div>
        <strong>Tracking Cookies Data</strong>
      </div>
      We use cookies and similar tracking technologies to track the activity on
      our Service and we hold certain information.
    </TextParagraph>
    <TextParagraph>
      Cookies are files with a small amount of data which may include an
      anonymous unique identifier. Cookies are sent to your browser from a
      website and stored on your device. Other tracking technologies are also
      used such as beacons, tags and scripts to collect and track information
      and to improve and analyze our Service.
    </TextParagraph>
    <TextParagraph>
      You can instruct your browser to refuse all cookies or to indicate when a
      cookie is being sent. However, if you do not accept cookies, you may not
      be able to use some portions of our Service.
    </TextParagraph>
    <TextParagraph>Examples of Cookies we use:</TextParagraph>
    <TextList as="ul">
      <li>Session Cookies: We use Session Cookies to operate our Service.</li>
      <li>Security Cookies: We use Security Cookies for security purposes.</li>
    </TextList>
    <TextHeader>Use of Data</TextHeader>
    <TextParagraph>
      UI Capsule uses the collected data for various purposes:
    </TextParagraph>
    <TextList as="ul">
      <li>to provide and maintain our Service;</li>
      <li>to notify you about changes to our Service;</li>
      <li>
        to allow you to participate in interactive features of our Service when
        you choose to do so;
      </li>
      <li>to provide customer support;</li>
      <li>
        to gather analysis or valuable information so that we can improve our
        Service;
      </li>
      <li>to monitor the usage of our Service;</li>
      <li>to detect, prevent and address technical issues;</li>
      <li>to fulfill any other purpose for which you provide it;</li>
      <li>
        to carry out our obligations and enforce our rights arising from any
        contracts entered into between you and us, including for billing and
        collection;
      </li>
      <li>
        to provide you with notices about your account and/or subscription,
        including expiration and renewal notices, email-instructions, etc.;
      </li>
      <li>
        to provide you with news, special offers and general information about
        other goods, services and events which we offer that are similar to
        those that you have already purchased or enquired about unless you have
        opted not to receive such information;
      </li>
      <li>
        in any other way we may describe when you provide the information;
      </li>
      <li>for any other purpose with your consent.</li>
    </TextList>
    <TextHeader>Retention of Data</TextHeader>
    <TextParagraph>
      We will retain your Personal Data only for as long as is necessary for the
      purposes set out in this Privacy Policy. We will retain and use your
      Personal Data to the extent necessary to comply with our legal obligations
      (for example, if we are required to retain your data to comply with
      applicable laws), resolve disputes, and enforce our legal agreements and
      policies.
    </TextParagraph>
    <TextParagraph>
      We will also retain Usage Data for internal analysis purposes. Usage Data
      is generally retained for a shorter period, except when this data is used
      to strengthen the security or to improve the functionality of our Service,
      or we are legally obligated to retain this data for longer time periods.
    </TextParagraph>
    <TextHeader>Disclosure of Data</TextHeader>
    <TextParagraph>
      We will never sell your data. However, there are two situations where we
      may disclose personal information that we collect, or you provide:
    </TextParagraph>
    <TextParagraph>
      <div>Disclosure for Law Enforcement.</div>
      Under certain circumstances, we may be required to disclose your Personal
      Data if required to do so by law or in response to valid requests by
      public authorities.
    </TextParagraph>
    <TextParagraph>
      <div>Business Transaction.</div>
      If we or our subsidiaries are involved in a merger, acquisition or asset
      sale, your Personal Data may be transferred.
    </TextParagraph>
    <TextHeader>Security of Data</TextHeader>
    <TextParagraph>
      The security of your data is important to us but remember that no method
      of transmission over the Internet or method of electronic storage is 100%
      secure. While we strive to use commercially acceptable means to protect
      your Personal Data, we cannot guarantee its absolute security.
    </TextParagraph>
    <TextHeader>Analytics</TextHeader>
    <TextParagraph>
      We may use third-party Service Providers to monitor and analyze the use of
      our Service. We currently use:
    </TextParagraph>
    <TextList as="ul">
      <li>
        <a
          href="https://firebase.google.com/policies/analytics"
          target="_blank"
          rel="noopener noreferrer"
        >
          Google Analytics for Firebase
        </a>
      </li>
      <li>
        <a
          href="https://firebase.google.com/support/privacy/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Firebase Crashlytics
        </a>
      </li>
    </TextList>
    <TextHeader>Links to Other Sites</TextHeader>
    <TextParagraph>
      Our Service may contain links to other sites that are not operated by us.
      If you click a third party link, you will be directed to that third
      party's site. We strongly advise you to review the Privacy Policy of every
      site you visit.
    </TextParagraph>
    <TextParagraph>
      We have no control over and assume no responsibility for the content,
      privacy policies or practices of any third party sites or services.
    </TextParagraph>
    <TextHeader>Changes to This Privacy Policy</TextHeader>
    <TextParagraph>
      We may update our Privacy Policy from time to time. We will notify you of
      any changes by posting the new Privacy Policy on this page.
    </TextParagraph>
    <TextParagraph>
      You are advised to review this Privacy Policy periodically for any
      changes. Changes to this Privacy Policy are effective when they are posted
      on this page.
    </TextParagraph>
    <TextHeader>Contact Us</TextHeader>
    <TextParagraph>
      If you have any questions about this Privacy Policy, please contact me by
      email: im.kaiyu@gmail.com
    </TextParagraph>
  </>
);

const PrivacyPage = () => (
  <>
    <Head>
      <title>Privacy Policy</title>
    </Head>
    <HeroSection
      bgColor="default"
      size="large"
      pt={{ xs: 12, sm: 20 }}
      pb={{ xs: 6, sm: 8 }}
    >
      <SectionHeader
        title="Privacy Policy"
        subtitle="How we collect and use your data"
        size={2}
      />
      <Content />
    </HeroSection>
  </>
);

PrivacyPage.Layout = SiteLayout;

export default PrivacyPage;
