import { cn } from "cn";
import {
  BuildingIcon,
  CalendarArrowUpIcon,
  DollarSignIcon,
  TargetIcon,
  UserCheckIcon,
  UserIcon,
} from "lucide-react";

import type { Person, PersonDepartment, PersonSkill } from "./types";
import type { ColumnConfig } from "./filter-package";

export const PERSON_DEPARTMENTS: PersonDepartment[] = [
  { color: "blue", id: "engineering", name: "Engineering" },
  { color: "purple", id: "design", name: "Design" },
  { color: "green", id: "product", name: "Product" },
  { color: "orange", id: "marketing", name: "Marketing" },
  { color: "red", id: "sales", name: "Sales" },
  { color: "pink", id: "hr", name: "Human Resources" },
  { color: "teal", id: "finance", name: "Finance" },
  { color: "indigo", id: "operations", name: "Operations" },
  { color: "emerald", id: "customer-success", name: "Customer Success" },
  { color: "cyan", id: "data", name: "Data & Analytics" },
  { color: "rose", id: "security", name: "Security" },
  { color: "violet", id: "legal", name: "Legal" },
] as const;

export const PERSON_SKILLS = [
  { color: "yellow", id: "javascript", level: "expert", name: "JavaScript" },
  { color: "blue", id: "typescript", level: "advanced", name: "TypeScript" },
  { color: "cyan", id: "react", level: "expert", name: "React" },
  { color: "green", id: "nodejs", level: "advanced", name: "Node.js" },
  { color: "yellow", id: "python", level: "intermediate", name: "Python" },
  { color: "red", id: "java", level: "advanced", name: "Java" },
  { color: "blue", id: "go", level: "beginner", name: "Go" },
  { color: "orange", id: "rust", level: "intermediate", name: "Rust" },
  { color: "indigo", id: "sql", level: "advanced", name: "SQL" },
  { color: "orange", id: "aws", level: "intermediate", name: "AWS" },
  { color: "blue", id: "docker", level: "advanced", name: "Docker" },
  {
    color: "blue",
    id: "kubernetes",
    level: "intermediate",
    name: "Kubernetes",
  },
  { color: "purple", id: "figma", level: "expert", name: "Figma" },
  { color: "yellow", id: "sketch", level: "advanced", name: "Sketch" },
  { color: "blue", id: "photoshop", level: "intermediate", name: "Photoshop" },
  {
    color: "orange",
    id: "illustrator",
    level: "beginner",
    name: "Illustrator",
  },
  { color: "green", id: "leadership", level: "expert", name: "Leadership" },
  {
    color: "pink",
    id: "communication",
    level: "advanced",
    name: "Communication",
  },
  {
    color: "teal",
    id: "project-management",
    level: "intermediate",
    name: "Project Management",
  },
  {
    color: "cyan",
    id: "data-analysis",
    level: "advanced",
    name: "Data Analysis",
  },
  {
    color: "purple",
    id: "machine-learning",
    level: "beginner",
    name: "Machine Learning",
  },
  { color: "rose", id: "ui-design", level: "expert", name: "UI Design" },
  {
    color: "indigo",
    id: "ux-research",
    level: "advanced",
    name: "UX Research",
  },
  {
    color: "emerald",
    id: "content-strategy",
    level: "intermediate",
    name: "Content Strategy",
  },
  { color: "lime", id: "seo", level: "beginner", name: "SEO" },
  {
    color: "pink",
    id: "social-media",
    level: "advanced",
    name: "Social Media",
  },
  {
    color: "blue",
    id: "email-marketing",
    level: "intermediate",
    name: "Email Marketing",
  },
  { color: "blue", id: "salesforce", level: "expert", name: "Salesforce" },
  { color: "orange", id: "hubspot", level: "advanced", name: "HubSpot" },
  {
    color: "green",
    id: "recruiting",
    level: "intermediate",
    name: "Recruiting",
  },
  {
    color: "purple",
    id: "training",
    level: "beginner",
    name: "Training & Development",
  },
  { color: "teal", id: "accounting", level: "advanced", name: "Accounting" },
  {
    color: "indigo",
    id: "budgeting",
    level: "intermediate",
    name: "Budgeting",
  },
  { color: "red", id: "compliance", level: "expert", name: "Compliance" },
  {
    color: "orange",
    id: "risk-management",
    level: "advanced",
    name: "Risk Management",
  },
  {
    color: "green",
    id: "customer-support",
    level: "intermediate",
    name: "Customer Support",
  },
  {
    color: "blue",
    id: "technical-writing",
    level: "beginner",
    name: "Technical Writing",
  },
  {
    color: "purple",
    id: "public-speaking",
    level: "advanced",
    name: "Public Speaking",
  },
  {
    color: "pink",
    id: "negotiation",
    level: "intermediate",
    name: "Negotiation",
  },
  {
    color: "emerald",
    id: "strategic-planning",
    level: "expert",
    name: "Strategic Planning",
  },
  {
    color: "cyan",
    id: "change-management",
    level: "advanced",
    name: "Change Management",
  },
  {
    color: "lime",
    id: "team-building",
    level: "intermediate",
    name: "Team Building",
  },
  { color: "rose", id: "mentoring", level: "beginner", name: "Mentoring" },
  {
    color: "violet",
    id: "conflict-resolution",
    level: "advanced",
    name: "Conflict Resolution",
  },
  {
    color: "amber",
    id: "time-management",
    level: "expert",
    name: "Time Management",
  },
  {
    color: "sky",
    id: "problem-solving",
    level: "expert",
    name: "Problem Solving",
  },
  {
    color: "indigo",
    id: "critical-thinking",
    level: "advanced",
    name: "Critical Thinking",
  },
  {
    color: "fuchsia",
    id: "creativity",
    level: "intermediate",
    name: "Creativity",
  },
  { color: "teal", id: "adaptability", level: "expert", name: "Adaptability" },
  {
    color: "pink",
    id: "emotional-intelligence",
    level: "advanced",
    name: "Emotional Intelligence",
  },
  {
    color: "green",
    id: "cross-cultural",
    level: "intermediate",
    name: "Cross-cultural Communication",
  },
  {
    color: "blue",
    id: "multilingual",
    level: "beginner",
    name: "Multilingual",
  },
] as const satisfies readonly PersonSkill[];

export const LABEL_STYLES_BG = {
  amber: "bg-amber-500",
  blue: "bg-blue-500",
  cyan: "bg-cyan-500",
  emerald: "bg-emerald-500",
  fuchsia: "bg-fuchsia-500",
  green: "bg-green-500",
  indigo: "bg-indigo-500",
  lime: "bg-lime-500",
  neutral: "bg-neutral-500",
  orange: "bg-orange-500",
  pink: "bg-pink-500",
  purple: "bg-purple-500",
  red: "bg-red-500",
  rose: "bg-rose-500",
  sky: "bg-sky-500",
  teal: "bg-teal-500",
  violet: "bg-violet-500",
  yellow: "bg-yellow-500",
} as const;

export type TW_COLOR = keyof typeof LABEL_STYLES_BG;

export const columnsConfig: readonly ColumnConfig<Person>[] = [
  {
    accessor: (row) => `${row.firstName} ${row.lastName}`,
    displayName: "Name",
    icon: UserIcon,
    id: "name",
    type: "text",
  },
  {
    accessor: (row) => row.department.id,
    displayName: "Department",
    icon: BuildingIcon,
    id: "department",
    options: PERSON_DEPARTMENTS.map((department) => ({
      icon: BuildingIcon,
      label: department.name,
      value: department.id,
    })),
    type: "option",
  },
  {
    accessor: (row) => row.salary,
    displayName: "Salary",
    icon: DollarSignIcon,
    id: "salary",
    max: 300_000,
    min: 20_000,
    type: "number",
  },
  {
    accessor: (row) => row.skills?.map((skill) => skill.id),
    displayName: "Skills",
    icon: TargetIcon,
    id: "skills",
    options: PERSON_SKILLS.map((skill) => ({
      icon: <div className={cn("size-2.5 rounded-full", LABEL_STYLES_BG[skill.color])} />,
      label: skill.name,
      value: skill.id,
    })),
    type: "multiOption",
  },
  {
    accessor: (row) => row.startDate,
    displayName: "Start Date",
    icon: CalendarArrowUpIcon,
    id: "startDate",
    type: "date",
  },
  {
    accessor: (row) => row.isActive,
    displayName: "Active employees",
    icon: UserCheckIcon,
    id: "isActive",
    toggledStateName: "active",
    type: "boolean",
  },
];
