import * as React from "react";

export const BuildingIcon = () => (
  <svg width="14" height="14" fill="none">
    <rect
      x="1.75"
      y="1.75"
      width="4.2"
      height="5.5"
      rx="1"
      stroke="#5C5E63"
      strokeWidth="1.1"
      strokeLinecap="round"
      strokeLinejoin="round"
    />
    <rect
      x="1.75"
      y="9.25"
      width="4.2"
      height="3"
      rx="1"
      stroke="#5C5E63"
      strokeWidth="1.1"
      strokeLinecap="round"
      strokeLinejoin="round"
    />
    <rect
      x="8.05"
      y="1.65"
      width="4.2"
      height="3"
      rx="1"
      stroke="#5C5E63"
      strokeWidth="1.1"
      strokeLinecap="round"
      strokeLinejoin="round"
    />
    <rect
      x="8.05"
      y="6.75"
      width="4.2"
      height="5.5"
      rx="1"
      stroke="#5C5E63"
      strokeWidth="1.1"
      strokeLinecap="round"
      strokeLinejoin="round"
    />
  </svg>
);
